FROM node:22-alpine

WORKDIR /app

# Install dependencies for Prisma
RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/payment-service/package*.json ./apps/payment-service/
COPY packages ./packages

RUN npm install

COPY apps/payment-service ./apps/payment-service
COPY .keys ./.keys

WORKDIR /app/apps/payment-service

RUN npx prisma generate

EXPOSE 3007

CMD ["npm", "run", "dev"]
