FROM node:22-alpine

WORKDIR /app

# Install dependencies for Prisma
RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/pricing-service/package*.json ./apps/pricing-service/
COPY packages ./packages

RUN npm install

COPY apps/pricing-service ./apps/pricing-service
COPY .keys ./.keys

WORKDIR /app/apps/pricing-service

RUN npx prisma generate

EXPOSE 3009

CMD ["npm", "run", "dev"]
