FROM node:22-alpine

WORKDIR /app

# Install dependencies for Prisma
RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/cart-service/package*.json ./apps/cart-service/
COPY packages ./packages

RUN npm install

COPY apps/cart-service ./apps/cart-service
COPY .keys ./.keys

WORKDIR /app/apps/cart-service

RUN npx prisma generate

EXPOSE 3005

CMD ["npm", "run", "dev"]
