FROM node:22-alpine

WORKDIR /app

# Install dependencies for Prisma
RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/order-service/package*.json ./apps/order-service/
COPY packages ./packages

RUN npm install

COPY apps/order-service ./apps/order-service
COPY .keys ./.keys

WORKDIR /app/apps/order-service

RUN npx prisma generate

EXPOSE 3006

CMD ["npm", "run", "dev"]
