FROM node:22-alpine

WORKDIR /app

# Install dependencies for Prisma
RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/catalog-service/package*.json ./apps/catalog-service/
COPY packages ./packages

RUN npm install

COPY apps/catalog-service ./apps/catalog-service
COPY .keys ./.keys

WORKDIR /app/apps/catalog-service

RUN npx prisma generate

EXPOSE 3004

CMD ["npm", "run", "dev"]
