FROM node:20-alpine AS dev
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
COPY apps/notification-service/package*.json ./apps/notification-service/
COPY packages/shared-types/package*.json ./packages/shared-types/
COPY packages/event-schemas/package*.json ./packages/event-schemas/
RUN npm install
COPY . .
RUN npx prisma generate --schema=apps/notification-service/prisma/schema.prisma
EXPOSE 3003
CMD ["npm", "run", "dev", "--workspace=@ecom/notification-service"]
