FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/storefront/package*.json ./apps/storefront/

RUN npm install

COPY apps/storefront ./apps/storefront

WORKDIR /app/apps/storefront

EXPOSE 4000

CMD ["npm", "run", "dev"]
